### PR TITLE
feat(maintainers): add maintainer

### PR DESCRIPTION
**Pull request by wanghong230**
Signed-off-by: Hong Wang <wanghong230@gmail.com>

### CODE REVIEW

**Review by alexmt — APPROVED** [review]
Both @wanghong230 and @jessesuen who represent Akuity are active members and maintainers of Argoproj. @rbreeze  and @terrytangyuan are approvers in both workflows and rollout. I 100% agree that Akuity should be listed as a maintainer. 

@edlee2121 , @hblixt  any objections?

**Comment by wanghong230** [comment]
Akuity is a corporate maintainer with all engineers to be core maintainers of Argo projects, delivering features and driving the community agendas. I believe we are qualified for the maintainer position.

https://github.com/argoproj/argoproj/blob/master/MAINTAINERS.md

**Comment by edlee2121** [comment]
I don't see a problem, but requires discussion in maintainers meeting before merge.

**Comment by alexec** [comment]
+1

**Review by sbose78 — APPROVED** [review]

**Comment by hblixt** [comment]
No objections from me.

**Comment by VaibhavPage** [comment]
+1

**Comment by edlee2121** [comment]
+1

**Comment by alexmt** [comment]
Sounds like we've got thumbs up from all maintainers. Thank you everyone!

**Comment by todaywasawesome** [comment]
Got my +1 in slack, but for the record :)

+1

**Comment by todaywasawesome** [comment]
@jessesuen When does the site go up? It's currently 404 😢

**Comment by simster7** [comment]
+1 for the record as well

**Pull request merged**
