### PR TITLE
docs: Upbound logo

### PR DESCRIPTION
**Pull request by vfarcic**
Added Upbound logo to the list

### CODE REVIEW

**Review by todaywasawesome — APPROVED** [review]
LGTM

**Comment by vfarcic** [comment]
@todaywasawesome I don't have permission to resolve the conflict. Can you do it?

**Comment by terrytangyuan** [comment]
@vfarcic You are working on your own fork so you should be able to rebase from the upstream master branch.

**Review by edlee2121 — APPROVED** [review]

**Comment by edlee2121** [comment]
@vfarcic Could you resolve the conflict so that we can merge?

**Comment by vfarcic** [comment]
It should be OK now @edlee2121

**Comment by edlee2121** [comment]
The diff doesn't look right. You may not have rebased your repo.
Do you mind resetting your repo and reapply your change to the top of master?
Thank you

**Comment by vfarcic** [comment]
It's a tiny change. Let me create a new PR...

**Pull request closed without merging**
