### PR TITLE
Add PathAI to list of Orgs

### PR DESCRIPTION
**Pull request by logankilpatrick**
This is my commit message

Signed-off-by: Logan Kilpatrick <Logan.kilpatrick@pathai.com>

### CODE REVIEW

**Comment by logankilpatrick** [comment]
@terrytangyuan Seems like the DCO failed the 2nd time despite it being a copy and paste from the first time...

**Comment by logankilpatrick** [comment]
Also, who is the right person to ping for a merge?

**Comment by logankilpatrick** [comment]
Supersedes #95

**Comment by terrytangyuan** [comment]
We should probably be able to merge as well. cc @alexmt Could you take a look?

**Review by alexmt — APPROVED** [review]
Looks good. Thank you@

**Comment by terrytangyuan** [comment]
@alexmt Would you like to go ahead and merge it? I don't have permission to this repo.

**Pull request merged**
