### PR TITLE
feat(maintainers): Add Pipekit to maintainers as corporate partner

### PR DESCRIPTION
**Pull request by atomicman57**
Closes: https://github.com/pipekit/oss-contributing/issues/60

Screenshot 2024-02-29 at 7 03 35 PM

### CODE REVIEW

**Review by jmeridth — APPROVED** [review]

**Review by agilgur5 — APPROVED** [review]

**Review by crenshaw-dev — APPROVED** [review]

**Comment by todaywasawesome** [comment]
I'm supportive of adding Pipekit as a corporate maintainer but I think we need to do a short writeup with the requirements just so it's not totally ad-hoc. In the past it's been a level of commitment to the project.

**Comment by agilgur5** [comment]
For reference here, Isitha (at Pipekit) brought this up in [the Maintainers Slack channel](https://cloud-native.slack.com/archives/C022F03E6BD/p1709267157329689) and Ed asked to bring it up in the next Maintainers Meeting, which I (no affiliation) did [today](https://docs.google.com/document/d/1C71GA0XCxsyGP7Q4SYveHak5ZZcJOuaOiDCt_xHG10U/edit#heading=h.aywjjtr02vuf).
 No objections in the meeting, strong support from various maintainers from different companies.
Ed, and Dan, per above, asked for a short summary. Crenshaw mentioned the [DevStats company contributions table](https://argo.devstats.cncf.io/d/5/companies-table?orgId=1&var-period_name=Last%20year&var-metric=contributions) as a potential loose criteria for inclusion.

**Comment by caelan-io** [comment]
Thank you @agilgur5 @todaywasawesome @crenshaw-dev @edlee2121  @jmeridth @terrytangyuan for the support on this PR and at the maintainers meeting today. Posting a summary list of our contributions and commitment to the Argo community on behalf of the whole Pipekit team:

- Contributors to Argo Workflows since 2021
- Contributors to Argo Helm since 2023
- 5th most active Argo contributing company in last year according to [devstats](https://argo.devstats.cncf.io/d/5/companies-table?orgId=1&var-period_name=Last%20year&var-metric=contributions)
- 2 Argo Workflows Maintainers (@joibel, @isubasinghe)
- 1 Argo Helm maintainer (@tico24)
- 4 Argo Workflows contributors (@tico24, @jpz13, @caelan-io, @atomicman57)
- 1 Argo CD contributor (@joibel)
- @joibel and @tico24 also maintain the most popular Argo CD plugin, [argocd-lovely-plugin](https://github.com/crumbhole/argocd-lovely-plugin)
- Our teammates respond to end-user questions in Slack daily
- We supported marketing, recruiting diverse speakers, reviewing proposals, and giving talks for each ArgoCon since 2021
- Host monthly Argo Workflows Community Meetings and Contributor Meetings
- Hold weekly Argo Workflows Office Hours
- Maintain free, open source Argo Workflows training course on [Killercoda](https://killercoda.com/argoproj/course/argo-workflows/)
- Wrote minor release notes with other maintainers for Argo Workflows v3.3 and v3.4 releases
- Coordinated 2023 Argo Workflows & Events end-user survey
- As a company, we provide Enterprise Support for Argo Workflows and help companies adopt Argo

**Comment by JPZ13** [comment]
Thanks, everyone. Would it be possible to merge and deploy this change?

**Comment by agilgur5** [comment]
I was going to bring it up in [tomorrow's Maintainer's meeting](https://docs.google.com/document/d/1C71GA0XCxsyGP7Q4SYveHak5ZZcJOuaOiDCt_xHG10U/edit#heading=h.clyfoymja17e) since it hadn't gotten merged yet; as I've said before, I think it's well deserved and overdue

**Review by terrytangyuan — APPROVED** [review]
+1 binding

**Review by todaywasawesome — APPROVED** [review]

**Review by crenshaw-dev — APPROVED** [review]

**Comment by zachaller** [comment]
+1 binding

**Comment by crenshaw-dev** [comment]
+1 binding

**Comment by christianh814** [comment]
+1 Sort of binding

**Review by christianh814 — APPROVED** [review]

**Comment by todaywasawesome** [comment]
@argoproj/members We'd like to have a formal vote to add Pipekit as an official maintainer and corporate partner of the Argo Project. Please vote below with +1 binding if you're a **maintainer** or +1 non-binding if you are not. Of course, you can also vote -1 binding and -1 non-binding. 

The vote will close in 14 days (June 19) @zachaller will review the votes.

**Comment by todaywasawesome** [comment]
+1 binding

**Review by sarabala1979 — APPROVED** [review]
+1 binding

**Comment by blakepettersson** [comment]
+1 non-binding

**Comment by morey-tech** [comment]
+1 non-binding

**Comment by kostis-codefresh** [comment]
+1 binding

**Comment by eduardodbr** [comment]
+1 non-binding

I would like to add that the support from pipekit was the reason why I started to contribute often to argo workflows

**Comment by rwong2888** [comment]
+1 non-binding

**Comment by agilgur5** [comment]
+1 binding

**Comment by Joibel** [comment]
As I have a conflict of interest here (Pipekit are my employer), I'll abstain.

**Comment by JPZ13** [comment]
I have an obvious conflict of interest as well, but we really appreciate the support, everyone. It means a lot to us 🙏

**Comment by hblixt** [comment]
+1 binding

**Comment by juliev0** [comment]
+1 binding

**Comment by jannfis** [comment]
+1 binding

**Comment by wtam2018** [comment]
+1 binding

**Comment by jmeridth** [comment]
+1 binding

**Comment by tczhao** [comment]
+1 binding

**Comment by my-git9** [comment]
+1 binding

**Comment by xianlubird** [comment]
+1 binding

**Comment by shuangkun** [comment]
+1 binding

**Comment by shmruin** [comment]
+1 binding

**Comment by sunyeongchoi** [comment]
+1 binding

**Review by pasha-codefresh — APPROVED** [review]

**Comment by edlee2121** [comment]
+1 binding

**Review by zachaller — APPROVED** [review]

**Pull request merged**
