### PR TITLE
Add PathAI to the list of companies / orgs using Argo

### PR DESCRIPTION
**Pull request by logankilpatrick**
At PathAI we have build our ML orchestration framework using Argo workflows and it has been amazing for us! We are excited to get more involved in the community and give back.

### CODE REVIEW

**Review by terrytangyuan — APPROVED** [review]
Thank you! Great to see you here. Would you also like to add it to this list? https://github.com/argoproj/argo-workflows/blob/master/USERS.md

**Comment by logankilpatrick** [comment]
Hey @terrytangyuan! I was just about to ping you : ) great to see you here as well!

**Comment by logankilpatrick** [comment]
Added: https://github.com/argoproj/argo-workflows/pull/8923

**Comment by logankilpatrick** [comment]
CC @alexmt

**Pull request closed without merging**
