### PR TITLE
docs: Add missing maintainers that have logos in the repo

### PR DESCRIPTION
**Pull request by terrytangyuan**
Based on https://github.com/argoproj/argoproj/blob/master/MAINTAINERS.md. There are two others that do not have logos on the repo yet and thus not included in this PR.

Signed-off-by: Yuan Tang <terrytangyuan@gmail.com>

### CODE REVIEW

**Comment by terrytangyuan** [comment]
cc @todaywasawesome @alexmt

**Comment by todaywasawesome** [comment]
On it!

**Review by todaywasawesome — APPROVED** [review]
Looks good

**Comment by terrytangyuan** [comment]
Thanks. Handing over to @alexmt to double check and merge.

**Comment by dtaniwaki** [comment]
Hi @terrytangyuan , thank you for adding my company logo to the site. Honestly speaking, I'm going to join another company next week. So, could you wait for a week before merging this PR, or remove my company for now? I'll send another PR to add the logo of the next company.

**Comment by terrytangyuan** [comment]
@dtaniwaki Done. Thanks for letting me know. 

@alexmt @todaywasawesome Is there any update on the process of getting this merged after the committee meeting?

**Comment by todaywasawesome** [comment]
@terrytangyuan there was some discussion about it and the consensus was that the maintainers here represent "corporate" maintainers. In other words, companies that have made or are making significant resource allocations to the project. That individuals at many companies make Argo successful is beyond doubt. We discussed changing the language on the section to be more clear. I should have a PR open this week. 

Happy for further discussion.

**Comment by terrytangyuan** [comment]
Thanks for the update. That makes sense. I am going to close this for now.

**Pull request closed without merging**
