### PR TITLE
feat(members): Add Ubie org to members

### PR DESCRIPTION
**Pull request by dtaniwaki**
I joined [Ubie](https://ubie.life/en). As we use Argo Workflows, Events and Rollouts, I added the company to the members.

### CODE REVIEW

**Comment by edlee2121** [comment]
@alexmt please review

**Comment by dtaniwaki** [comment]
@alexmt Could you review this PR?

**Review by todaywasawesome — APPROVED** [review]
Looks good! Sorry it took so long to review!

**Comment by dtaniwaki** [comment]
@todaywasawesome Thank you for reviewing the change. Would you mind merging it?

**Review by edlee2121 — APPROVED** [review]

**Pull request merged**
